title: Suhe Repo
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Suhe Repo
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

# topnav_banner: "ELIXIR toolkit theme is currently under development and may change at any point - it is not meant for production use"
# Optional: a banner message to display to users on all pages

description: "Just the documents to share."
# Metadata description of the website

dsw_deep_link_prefix:
# prefix for DSW deep links to a certain question

gtag:
# Google analytics tag

matomo:
# Matomo domain where Matomo is running
matomo_id:
# Integer indicating the Matomo Website ID
matomo_cookies: true
# Boolean that determines whether a Matomo tracking cookie is used or not

plausible:
# Plausible tag
plausible_src:
# default: 'https://plausible.io/js/plausible.js

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

sass:
    style: compressed

defaults:
# Define here page metadata attributes for all pages at once or on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      # sidebar: main
      sidebar: []

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick


theme_variables:
  # git_host: GitHub
  # back_to_top: true
  # dev-info-banner: false
  # privacy_statement_url: /privacy
  # github_buttons:
  #   position: top
  #   edit_me: true
  #   open_issue: true
  #   history: true
  # datatables:
  #   searchbuilder: True
  # headings:
  #   related-pages: Related pages
  #   more-information-tiles: More information
  #   resource-table-all: Tools and resources on this page
  #   resource-table-all-collapse: false
  #   affiliation-tiles-page: Affiliations
  #   contributor-minitiles-page: Contributors
  toc:
    min_headings: 1
    headings: 'h1,h2'
  topnav:
    theme: light
    # brand_logo: assets/img/main_logo.svg
    # github: true
    # twitter: false
    # bluesky: false
    # linkedin: false
    # fosstodon: false
  # theme_color: 0d6efd
  # fonts:
  #   - url towards a font
  # breadcrumb: false

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme
